name: "N8N Webhook Trigger"
description: "Triggers an N8N workflow via a webhook with GitHub environment variables"
inputs:
  webhook-url:
    description: "The N8N webhook URL"
    required: true

runs:
  using: composite
  steps:
    - name: Inform N8N
      shell: bash
      run: |
        # Collect all environment variables starting with GITHUB_
        github_env_vars=$(env | grep '^GITHUB_')

        # Convert collected variables to JSON format
        json_payload=$(echo "$github_env_vars" | awk 'BEGIN { printf "{"; first=1 } { split($0, arr, "="); if (!first) printf ","; printf "\"" arr[1] "\":\"" arr[2] "\""; first=0 } END { printf "}" }')

        # Print JSON payload for debugging (optional)
        echo "JSON Payload: $json_payload"

        # Send the JSON payload via a POST request using curl
        curl -X POST -H "Content-Type: application/json" -d "$json_payload" ${{ inputs.webhook-url }}
