name: "N8N Webhook Trigger"
description: "Triggers an N8N workflow via a webhook with GitHub environment variables"
inputs:
  webhook-url:
    description: "The N8N webhook URL"
    required: true

runs:
  using: composite
  steps:
    - name: Inform N8N
      shell: bash
      run: |
        # Collect all environment variables starting with GITHUB_
        github_env_vars=$(env | grep '^GITHUB_')

        # Extract committer's name, commit message, and branch
        committer_name=$(git log -1 --pretty=format:'%cn')
        commit_message=$(git log -1 --pretty=format:'%s')
        branch_name=${GITHUB_REF##*/}

        # Convert collected variables to JSON format
        json_payload=$(echo "$github_env_vars" | awk 'BEGIN { printf "{"; first=1 }
        {
          split($0, arr, "=");
          if (!first) printf ","; 
          printf "\"" arr[1] "\":\"" arr[2] "\"";
          first=0
        }
        END { printf "}" }')

        # Append committer's name, commit message, and branch to JSON payload
        json_payload=$(echo "$json_payload" | jq --arg committer_name "$committer_name" \
        --arg commit_message "$commit_message" \
        --arg branch_name "$branch_name" \
        '. + {committer_name: $committer_name, commit_message: $commit_message, branch_name: $branch_name}')

        # Print JSON payload for debugging (optional)
        echo "JSON Payload: $json_payload"

        # Send the JSON payload via a POST request using curl
        curl -X POST -H "Content-Type: application/json" -d "$json_payload" ${{ inputs.webhook-url }}
